### ISSUE TITLE
Crashes in Bun

### ISSUE THREAD

**Issue by lenovouser** [SerCeMan/firewalker#44]
I am not sure if this an issue on Bun's side or here, but I thought I would start here, let me know if I should post this at the Bun repository instead.

When importing firewalker the following happens:

```
55 |     'node=' + process.versions.node,
56 |     process.versions.electron ? 'electron=' + process.versions.electron : '',
57 |     typeof __webpack_require__ === 'function' ? 'webpack=true' : '' // eslint-disable-line
58 |   ].filter(Boolean).join(' ')
59 |
60 |   throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
             ^
error: No native build was found for platform=darwin arch=arm64 runtime=node abi=127 uv=1 armv=8 libc=glibc node=22.6.0
    loaded from: /Users/silas/Workspace/panascais/projects/experiments/node_modules/.pnpm/ref-napi@3.0.3/node_modules/ref-napi

      at /Users/silas/Workspace/panascais/projects/experiments/node_modules/.pnpm/node-gyp-build@4.8.2/node_modules/node-gyp-build/node-gyp-build.js:60:9
      at load (/Users/silas/Workspace/panascais/projects/experiments/node_modules/.pnpm/node-gyp-build@4.8.2/node_modules/node-gyp-build/node-gyp-build.js:22:30)
      at /Users/silas/Workspace/panascais/projects/experiments/node_modules/.pnpm/ref-napi@3.0.3/node_modules/ref-napi/lib/ref.js:8:18
      at /Users/silas/Workspace/panascais/projects/experiments/node_modules/.pnpm/ffi-napi@4.0.3/node_modules/ffi-napi/lib/ffi.js:7:7
      at /Users/silas/Workspace/panascais/projects/experiments/node_modules/.pnpm/firewalker@1.0.9/node_modules/firewalker/dist/wirefilter.js:17:20
      at /Users/silas/Workspace/panascais/projects/experiments/node_modules/.pnpm/firewalker@1.0.9/node_modules/firewalker/dist/firewall.js:24:7

Bun v1.1.34 (macOS arm64)
```

**Comment by SerCeMan** [comment]
Thanks, @lenovouser! This has been resolved with https://github.com/SerCeMan/firewalker/pull/48. Please re-open the issue if it's still failing for you.
